version: '3.0'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bobobox_test
    volumes:
    - ./data:/var/lib/mysql
  app:
    ports: 
      - 8080:8080 
    build:
      context : .
      dockerfile: ./Dockerfile
    command : "go run main.go"
    links:
      - mysql